// Original editorial seed. Never import this answer-bearing module into client code.
import type { CompanyContext, Level, PublicQuestion, Reference } from "../assessment.ts";

export type BankQuestion = PublicQuestion & {
  level: Level; correct: string[]; explanation: string; references: Reference[];
  status: "published" | "draft" | "retired";
  collection?: "book";
};
const refs = {
  java: { title: "Oracle: Java language basics", url: "https://dev.java/learn/language-basics/" },
  oop: { title: "Oracle: classes and objects", url: "https://dev.java/learn/classes-objects/" },
  collections: { title: "Oracle: collections framework", url: "https://dev.java/learn/api/collections-framework/" },
  exceptions: { title: "Oracle: exceptions", url: "https://dev.java/learn/exceptions/" },
  spring: { title: "Spring: dependency injection", url: "https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html" },
  rest: { title: "Spring: building a REST service", url: "https://spring.io/guides/gs/rest-service" },
  sql: { title: "PostgreSQL: querying a table", url: "https://www.postgresql.org/docs/current/tutorial-select.html" },
  transactions: { title: "PostgreSQL: transactions", url: "https://www.postgresql.org/docs/current/tutorial-transactions.html" },
  outbox: { title: "Debezium: transactional outbox", url: "https://debezium.io/documentation/reference/stable/transformations/outbox-event-router.html" },
  retry: { title: "Resilience4j: bounded retries", url: "https://resilience4j.readme.io/docs/retry" },
  jpa: { title: "Spring: accessing data with JPA", url: "https://spring.io/guides/gs/accessing-data-jpa" },
  testing: { title: "Spring Boot: testing", url: "https://docs.spring.io/spring-boot/reference/testing/index.html" },
  git: { title: "Git tutorial", url: "https://git-scm.com/docs/gittutorial" },
  linux: { title: "GNU: directory listing", url: "https://www.gnu.org/software/coreutils/manual/html_node/ls-invocation.html" },
  maven: { title: "Apache Maven: build lifecycle", url: "https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html" },
  security: { title: "Spring Security: authorization", url: "https://docs.spring.io/spring-security/reference/servlet/authorization/index.html" },
  docker: { title: "Docker: containers", url: "https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/" },
  ci: { title: "GitHub: continuous integration", url: "https://docs.github.com/en/actions/about-github-actions/understanding-github-actions" },
  ai: { title: "Spring AI: concepts", url: "https://docs.spring.io/spring-ai/reference/concepts.html" },
  tools: { title: "Spring AI: tool calling", url: "https://docs.spring.io/spring-ai/reference/api/tools.html" },
  observations: { title: "Spring Boot: observability", url: "https://docs.spring.io/spring-boot/reference/actuator/observability.html" },
  threads: { title: "Oracle: concurrency", url: "https://docs.oracle.com/javase/tutorial/essential/concurrency/" },
  virtual: { title: "Oracle: virtual threads", url: "https://dev.java/learn/new-features/virtual-threads/" },
  kafka: { title: "Apache Kafka: design", url: "https://kafka.apache.org/41/design/design/" },
  gc: { title: "Oracle: garbage collection", url: "https://dev.java/learn/jvm/tool/garbage-collection/" },
  jfr: { title: "Oracle: JDK Flight Recorder", url: "https://dev.java/learn/jvm/jfr/" },
  cache: { title: "Spring: cache abstraction", url: "https://docs.spring.io/spring-framework/reference/integration/cache.html" },
  k8s: { title: "Kubernetes: Pod lifecycle", url: "https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/" },
  evaluation: { title: "Spring AI: evaluation testing", url: "https://docs.spring.io/spring-ai/reference/api/testing.html" },
} satisfies Record<string, Reference>;

type Seed = [string, string[], number[], string, keyof typeof refs, string?];
// Every question has a stable ID and revision. Changes to wording, keys or explanations
// require a version bump; existing sessions keep their immutable question snapshots.
function group(topic: string, level: Level, difficulties: number[], seeds: Seed[], offset = 0): BankQuestion[] {
  return seeds.map(([prompt, options, correct, explanation, ref, tag], index) => ({
    id: `${topic}-${index + offset + 1}`, version: 1, topic, level,
    tags: [topic, ...(tag ? [tag] : [])], complexity: difficulties[index],
    type: correct.length === 1 ? "single" : "multiple", prompt,
    options: options.map((text, i) => ({ id: String.fromCharCode(97 + i), text })),
    correct: correct.map((i) => String.fromCharCode(97 + i)), explanation,
    source: { title: `Original question · Reference: ${refs[ref].title}`, url: refs[ref].url },
    references: [refs[ref]], companyContexts: [] as CompanyContext[], status: "published",
  }));
}

export const questionBank: BankQuestion[] = [
  ...group("core-java", "Junior", [0, 2, 4], [
    ["What is an object in Java?", ["An instance of a class", "A source-code folder", "A compiler option", "A database table"], [0], "A class describes a type; an object is an instance with its own state.", "oop", "oop"],
    ["Which choices support encapsulation? Select all that apply.", ["Keep internal fields private", "Expose every field publicly", "Validate changes through methods", "Put unrelated classes in one file"], [0, 2], "Encapsulation controls access to state so the object can preserve its rules.", "oop", "oop"],
    ["Two different String objects contain the same text. How should you compare their contents?", ["Use ==", "Use equals()", "Compare their memory addresses", "Convert both to Object and use =="], [1], "equals() compares String contents. == compares whether references point to the same object.", "java"],
  ]),
  ...group("collections", "Junior", [1, 2, 4], [
    ["You need to look up a user by a unique ID. Which collection best expresses this?", ["List of unrelated values", "Set of user names", "Map from ID to user", "Queue of events"], [2], "A Map associates a key with a value and supports lookup by that key.", "collections"],
    ["Which statements describe a Set? Select all that apply.", ["It rejects duplicate elements according to its equality rules", "Every Set keeps insertion order", "It is useful for tracking unique values", "It always supports access by numeric index"], [0, 2], "Sets model uniqueness. Ordering depends on the implementation; numeric indexing is a List concept.", "collections"],
    ["A file operation can fail. Which approach makes the failure easiest for callers to handle?", ["Catch the exception and silently return success", "Remove all error handling", "Return random data", "Handle it meaningfully or propagate an informative exception"], [3], "A caller needs an honest failure signal. Handle an error where recovery is possible, otherwise preserve useful context.", "exceptions"],
  ]),
  ...group("spring", "Junior", [1, 2, 4], [
    ["What is the main purpose of dependency injection?", ["Let an object receive the collaborators it needs", "Turn Java into SQL", "Remove the need for tests", "Make every object global"], [0], "Supplying dependencies separates construction from use and makes collaborators easier to replace in tests.", "spring"],
    ["Which practices suit a REST endpoint that creates a resource? Select all that apply.", ["Change data through a GET request", "Validate the request", "Return a meaningful HTTP status", "Always return success, even on failure"], [1, 2], "Validate inputs and communicate the outcome through HTTP semantics, such as 201 for successful creation.", "rest"],
    ["A service needs a repository. Why is constructor injection useful?", ["It makes the repository a database table", "It exposes required dependencies and allows test substitutes", "It eliminates all runtime errors", "It automatically commits every transaction"], [1], "The constructor makes required collaborators explicit. Tests can provide a fake or mock repository.", "spring"],
  ]),
  ...group("data", "Junior", [1, 2, 4], [
    ["Which SQL clause filters individual rows by a condition?", ["ORDER BY", "SELECT", "WHERE", "LIMIT"], [2], "WHERE filters rows. ORDER BY sorts them and LIMIT bounds the result size.", "sql"],
    ["What does a transaction help achieve when two related updates must succeed together?", ["Both updates commit, or neither takes effect", "Every query becomes faster", "No constraints are needed", "Data is permanently kept in memory"], [0], "Atomicity treats related changes as one unit: commit them together or roll them back.", "transactions"],
    ["Which statements about JPA are correct? Select all that apply.", ["JPA removes the need to understand SQL", "Entities represent persisted application data", "Database constraints no longer matter", "Repositories can provide common persistence operations"], [1, 3], "JPA maps application objects to relational data. SQL behavior, transactions and database constraints still matter.", "jpa", "jpa"],
  ]),
  ...group("testing", "Junior", [1, 2, 4], [
    ["What does a focused unit test usually check?", ["The entire deployed system at once", "A small behavior in isolation", "Only the source-code formatting", "Whether a developer memorized syntax"], [1], "Unit tests provide fast feedback about a small behavior, with external dependencies controlled.", "testing"],
    ["An AI assistant generates a service method. What should you do before accepting it? Select all that apply.", ["Review its behavior against the requirements", "Accept it because it compiles", "Check failure cases with tests", "Assume its dependencies are always valid"], [0, 2], "Treat generated code as a proposal: understand it and test intended behavior and failures.", "testing", "responsible-ai"],
    ["A mocked repository test passes, but the real query fails. Which test would best expose this?", ["A screenshot of the IDE", "The same mocked test repeated", "An integration test against a representative database", "A test that only checks method names"], [2], "Integration tests exercise boundaries such as real SQL, mappings and constraints that mocks do not verify.", "testing"],
  ]),
  ...group("tools", "Junior", [1, 2, 4], [
    ["In a Linux terminal, what does ls normally do?", ["List directory contents", "Delete the current directory", "Create a Git commit", "Compile Java"], [0], "ls lists files and directories. It is a basic navigation and inspection tool.", "linux", "linux"],
    ["Which Git actions help you prepare a deliberate commit? Select all that apply.", ["Inspect changes with git diff", "Delete the repository history", "Check staged and unstaged changes with git status", "Commit secrets so collaborators can use them"], [0, 2], "Review the diff and status before staging and committing a coherent change.", "git", "git"],
    ["Why use Maven or Gradle in a Java project?", ["To replace the JVM", "To manage dependencies and repeatable build tasks", "To automatically solve every production failure", "To avoid version control"], [1], "Build tools coordinate compilation, dependencies, tests and packaging so the process is repeatable.", "maven", "build-tools"],
  ]),
  ...group("security", "Mid", [2, 4, 7], [
    ["What is the difference between authentication and authorization?", ["They are always identical", "Authentication identifies a caller; authorization decides allowed actions", "Authorization only encrypts traffic", "Authentication grants every permission"], [1], "Knowing who made a request does not by itself establish permission to access a resource.", "security"],
    ["A signed-in user requests another user's private order by ID. What should the API do?", ["Allow access because the user signed in", "Trust that the ID was hidden in the UI", "Check permission to access that specific order", "Only check whether the ID is numeric"], [2], "Enforce access to the requested resource on the server, including ownership or an explicit permission.", "security"],
    ["Which measures help protect a sensitive API? Select all that apply.", ["Enforce least privilege", "Rely exclusively on hidden frontend buttons", "Check authorization on every protected operation", "Treat possession of any valid token as unrestricted access"], [0, 2], "Apply narrowly scoped permissions at the server boundary. Client UI controls are not an authorization boundary.", "security"],
  ]),
  ...group("delivery", "Mid", [2, 4, 7], [
    ["What does a container package for an application?", ["Only a screenshot", "The host computer's entire physical hardware", "The application and its runtime dependencies", "Every production secret by default"], [2], "Containers package an application environment and isolate its processes while sharing the host kernel.", "docker"],
    ["Which checks belong in a useful CI pipeline? Select all that apply.", ["Build the application", "Run automated tests", "Skip checks on pull requests", "Publish credentials into build logs"], [0, 1], "Automated builds and tests expose regressions early and make integration repeatable.", "ci", "ci-cd"],
    ["A containerized service passes unit tests. What gives stronger confidence before deployment?", ["Rebuild until the image is smaller", "An integration test using the image and representative dependencies", "Rename the image tag to stable", "Remove health checks"], [1], "Testing the deployable image with its dependencies checks configuration and integration beyond isolated code.", "docker"],
  ]),
  ...group("ai", "Mid", [2, 4, 7], [
    ["What does retrieval-augmented generation (RAG) add to a model request?", ["Relevant retrieved information", "A guarantee of perfect accuracy", "Unlimited context", "Automatic retraining of all model weights"], [0], "RAG supplies relevant material at request time. It improves grounding but still needs evaluation.", "ai", "rag"],
    ["What are embeddings useful for in a retrieval system?", ["Encrypting private documents", "Replacing access controls", "Representing content so semantic similarity can be compared", "Guaranteeing that every answer is correct"], [2], "Embeddings encode features into vectors that can support similarity search.", "ai", "embeddings"],
    ["A model proposes a tool call in a Java service. Which responsibilities remain with the application? Select all that apply.", ["Validate the arguments", "Execute every proposal without checks", "Authorize the requested action", "Trust model text as executable code"], [0, 2], "The application controls execution. Validate and authorize a proposed call before allowing effects.", "tools", "tool-calling"],
  ]),
  ...group("observability", "Mid", [2, 4, 7], [
    ["Which signal is best for tracking the rate of failed HTTP requests over time?", ["A metric", "A method name", "A Git branch", "A source file's length"], [0], "Metrics summarize numeric behavior over time, including request counts and error rates.", "observations"],
    ["A request travels through several services and becomes slow. What helps locate the delay?", ["A larger application logo", "Distributed traces with correlated spans", "Removing all timestamps", "Only counting source-code lines"], [1], "A trace follows work across boundaries; span durations reveal where time is spent.", "observations"],
    ["Which observability practices are useful? Select all that apply.", ["Include raw passwords in logs", "Correlate logs with trace identifiers", "Use an unbounded user ID label on every metric", "Track latency distributions and error rates"], [1, 3], "Correlated signals support diagnosis. Protect sensitive data and avoid unbounded metric label cardinality.", "observations"],
  ]),
  ...group("concurrency", "Senior", [3, 6, 9], [
    ["Two threads update shared mutable state without coordination. What risk does this introduce?", ["Automatic serialization", "A race condition", "Guaranteed faster execution", "Compile-time deadlock detection"], [1], "Interleaved operations can violate assumptions about reads and writes to shared state.", "threads", "multithreading"],
    ["Which approaches can reduce shared-state concurrency bugs? Select all that apply.", ["Prefer immutable values where practical", "Assume reads and writes always happen in order", "Use appropriate synchronization or atomic operations", "Add arbitrary sleeps as a correctness guarantee"], [0, 2], "Reduce shared mutation and coordinate the state that must remain shared. Timing delays are not synchronization.", "threads"],
    ["A Java service performs many blocking network calls. What is a reasonable expectation of virtual threads?", ["They make CPU-bound calculations inherently faster", "They remove downstream capacity limits", "They can support many waiting tasks, while downstream concurrency still needs bounds", "They eliminate the need for timeouts"], [2], "Virtual threads reduce the cost of waiting tasks. They do not create CPU or database capacity; keep timeouts and limits.", "virtual"],
  ]),
  ...group("distributed", "Senior", [3, 6, 10], [
    ["A consumer may receive the same event more than once. What property helps it process safely?", ["Idempotency", "Longer variable names", "No error handling", "Random partition keys"], [0], "An idempotent handler prevents a repeated event from causing a repeated business effect.", "kafka", "idempotency"],
    ["Which statements about Kafka ordering and consumption are correct? Select all that apply.", ["Ordering is defined within a partition", "All partitions provide one global order", "Retries or replay can require duplicate-safe processing", "A consumer can ignore failure recovery"], [0, 2], "Partitioning defines ordering boundaries. Consumers must account for replay and their delivery guarantees.", "kafka"],
    ["An order service must update its database and reliably publish an event. What does a transactional outbox address?", ["It makes all remote calls one local transaction", "It records the change and pending event atomically, then relays with duplicate handling", "It removes the need for consumers", "It guarantees every external side effect happens exactly once"], [1], "A local transaction records both state and an event to relay. Relay retries still need idempotent consumers.", "outbox", "outbox"],
  ]),
  ...group("performance", "Senior", [3, 6, 9], [
    ["What does Java garbage collection primarily reclaim?", ["All files on disk", "Memory occupied by unreachable objects", "Every object after each method call", "Open database transactions"], [1], "GC reclaims heap memory from unreachable objects. It does not replace explicit management of external resources.", "gc", "garbage-collector"],
    ["Which questions matter before caching a frequently read value? Select all that apply.", ["How stale the value may be", "Whether cache keys have the correct scope", "Whether caching makes authorization unnecessary", "Whether the cache has infinite memory"], [0, 1], "Define freshness and key boundaries. Caches consume finite resources and must preserve isolation.", "cache"],
    ["A Java service slows down under load. What is the best first step before changing GC settings?", ["Choose random JVM flags", "Disable all monitoring", "Measure CPU, allocations, GC and dependency latency under representative load", "Rewrite every class"], [2], "Profile first to distinguish CPU, allocation, GC and external bottlenecks. Tune against observed evidence.", "jfr", "jvm"],
  ]),
  ...group("operations", "Senior", [3, 6, 9], [
    ["What does a readiness probe communicate to Kubernetes?", ["Whether a container image was free", "Whether a Pod should receive service traffic", "Whether all database migrations are reversible", "Whether developers are logged in"], [1], "Readiness controls participation in Service traffic; a running process may not yet be ready.", "k8s"],
    ["Which choices improve resilience when a downstream service is slow? Select all that apply.", ["Bound request time with timeouts", "Retry instantly forever", "Use bounded retries with backoff where the operation is safe to retry", "Allow an unlimited queue of pending requests"], [0, 2], "Bound waiting and retries to prevent overload. Retried operations must account for duplicate effects.", "retry"],
    ["A shared database briefly fails. Why can restarting every API Pod on a dependency-based liveness failure be harmful?", ["It automatically repairs the database", "It guarantees no requests are lost", "It can create restart storms without repairing the dependency", "It makes readiness probes unnecessary"], [2], "Liveness restarts should target recoverable local failure. Shared dependency outages can otherwise cascade into restart storms.", "k8s"],
  ]),
  ...group("agents", "Senior", [3, 6, 10], [
    ["What is an evaluation set useful for when changing an AI application?", ["Comparing behavior on representative cases", "Proving it can never fail", "Replacing all access controls", "Making every model response identical"], [0], "A stable set of representative tasks lets you compare quality and regressions across changes.", "evaluation"],
    ["Which controls are useful for an agent that calls tools repeatedly? Select all that apply.", ["A bounded number of steps and cost budget", "Unlimited retries until the model stops", "Per-tool authorization and argument validation", "Allowing tools to bypass application permissions"], [0, 2], "Bound execution and enforce permissions at every tool boundary, including when using MCP-connected tools.", "tools", "mcp"],
    ["A cheaper model reduces cost but fails more important tasks. How should you assess the change?", ["Ship based only on price per token", "Ignore latency and retry costs", "Compare task success, safety, end-to-end latency and total cost on representative workloads", "Measure only response length"], [2], "Evaluate the whole system: retries, tool use, task outcomes, latency and cost. A cheaper call may make a task more expensive.", "evaluation"],
  ]),
  ...group("core-java", "Junior", [0, 2, 4, 0, 2, 4], [
    ["Which statement about a local variable in Java is correct?", ["It must be assigned before it is read", "It is always initialized to null", "It is shared by every object", "It can only store text"], [0], "The compiler requires a local variable to be definitely assigned before it is read.", "java"],
    ["A subclass overrides a method and an instance is referenced by its parent type. Which implementation runs?", ["Always the parent implementation", "The implementation selected from the runtime object", "Both implementations at once", "The compiler rejects the reference"], [1], "For an overridden instance method, dynamic dispatch selects the implementation of the runtime object.", "oop", "oop"],
    ["What does try-with-resources provide for an AutoCloseable resource?", ["It closes the resource when the statement finishes, including exceptional paths", "It keeps the resource open forever", "It suppresses every exception", "It converts the resource to a static field"], [0], "Try-with-resources reliably closes declared AutoCloseable resources when control leaves the statement.", "exceptions"],
    ["What does static mean for a Java field?", ["The field belongs to each method call", "The field belongs to the class rather than an individual instance", "The field can never change", "The field is stored in a database"], [1], "A static field is associated with the class and is shared by its instances.", "java"],
    ["Why define a Java interface?", ["To describe a contract that different implementations can satisfy", "To allocate database storage", "To prevent all polymorphism", "To make every method private"], [0], "An interface expresses a contract independently of a particular implementation.", "oop", "oop"],
    ["If two objects are equal according to equals(), what must a correct hashCode() implementation guarantee?", ["Their hash codes are different", "Their hash codes are equal", "Their memory addresses are equal", "Their fields are all public"], [1], "Equal objects must produce equal hash codes so hash-based collections can locate them consistently.", "collections"],
  ], 3),
  ...group("collections", "Junior", [1, 2, 4, 1, 2, 4], [
    ["You need ordered elements, duplicates, and access by position. Which abstraction fits best?", ["List", "Set", "Map", "Optional"], [0], "A List preserves a sequence, permits duplicates, and exposes positional access.", "collections"],
    ["How can you safely remove the current element while iterating a mutable collection?", ["Call the iterator's remove operation where supported", "Modify it from an unrelated thread", "Clear the collection inside every loop", "Ignore the collection contract"], [0], "The iterator's supported removal operation keeps iteration state consistent.", "collections"],
    ["Why is a mutable object risky as a HashMap key?", ["Changing equality-relevant state can make the entry unreachable by lookup", "HashMap copies every object to disk", "Keys must always be numbers", "Mutable objects cannot implement equals()"], [0], "A key whose hash or equality changes after insertion may no longer be found in its original bucket.", "collections"],
    ["Which collection abstraction naturally models first-in, first-out work?", ["Queue", "Set", "Map", "Stack trace"], [0], "A Queue models elements waiting to be processed, commonly in FIFO order.", "collections"],
    ["You only need fast membership checks and unique values. Which collection is the clearest choice?", ["Set", "List", "StringBuilder", "Thread"], [0], "A Set directly expresses uniqueness and membership.", "collections"],
    ["A method returns an unmodifiable list. What does that promise to its caller?", ["The caller cannot mutate the list through that reference", "The element objects become deeply immutable", "The source collection can never change", "The list is stored outside the JVM"], [0], "An unmodifiable view blocks structural changes through that view; it does not automatically make elements deeply immutable.", "collections"],
  ], 3),
  ...group("spring", "Junior", [1, 2, 4, 1, 2, 4], [
    ["What does @RestController indicate in a Spring application?", ["The class handles web requests and writes response bodies", "The class is a database table", "The class can only run tests", "The class replaces the JVM"], [0], "A REST controller maps web requests and returns data in the HTTP response body.", "rest"],
    ["What is Spring's default scope for a regular application bean?", ["One instance per method call", "Singleton within the application context", "One instance per database row", "A new process per request"], [1], "The default bean scope is singleton within a Spring application context.", "spring"],
    ["Why may calling a @Transactional method from another method on the same object fail to start the expected transaction?", ["The self-call can bypass the Spring proxy that applies transaction advice", "Transactions only work in controllers", "Java forbids method calls on this", "The database ignores annotations"], [0], "In proxy-based transaction management, self-invocation does not pass through the proxy that applies the interceptor.", "spring"],
    ["What is @RequestBody commonly used for?", ["Binding an HTTP request body to a method parameter", "Creating a Git branch", "Opening a database transaction", "Scheduling garbage collection"], [0], "@RequestBody asks Spring to deserialize the request body into the declared parameter type.", "rest"],
    ["Why keep HTTP mapping in a controller and business rules in a service?", ["It separates transport concerns from reusable application behavior", "It removes the need for validation", "It guarantees every query is fast", "It makes all fields public"], [0], "Separating transport and business concerns improves reuse, testing, and clarity.", "spring"],
    ["A service changes two related records. Where should the transaction boundary normally be placed?", ["Around the complete business operation", "Around each individual field assignment", "Only in the browser", "After the response has been sent"], [0], "A transaction should cover the business operation whose database changes must succeed or fail together.", "transactions"],
  ], 3),
  ...group("data", "Junior", [1, 2, 4, 1, 2, 4], [
    ["What is the purpose of a primary key?", ["Uniquely identify a table row", "Sort every query automatically", "Encrypt the table", "Replace all indexes"], [0], "A primary key enforces a stable unique identity for each row.", "sql"],
    ["What is a common trade-off of adding a database index?", ["Reads may improve while writes and storage cost increase", "All writes become free", "Constraints stop working", "Transactions are disabled"], [0], "Indexes can accelerate matching and ordering, but they consume space and must be maintained on writes.", "sql"],
    ["What does an optimistic-lock version column help detect?", ["A concurrent update based on stale data", "A missing Java compiler", "An expired TLS certificate", "A slow network cable"], [0], "The version changes with an update, allowing a stale writer to be rejected instead of silently overwriting newer data.", "jpa", "jpa"],
    ["What does a SQL JOIN do?", ["Combine related rows from tables according to a condition", "Permanently merge two databases", "Delete duplicate Java objects", "Start a web server"], [0], "A JOIN produces rows by relating records from its input tables using a join condition.", "sql"],
    ["Why use parameterized SQL instead of concatenating user input?", ["It separates values from SQL structure and reduces injection risk", "It makes authorization unnecessary", "It guarantees every query uses an index", "It turns SQL into Java bytecode"], [0], "Parameters keep untrusted values from being interpreted as SQL syntax.", "sql"],
    ["What is the JPA N+1 query problem?", ["Loading a collection triggers one initial query followed by many related queries", "A transaction commits eleven times", "A table has too many primary keys", "A query returns exactly N plus one rows"], [0], "Lazy relationship access can cause one query for roots and an additional query for each root's related data.", "jpa", "jpa"],
  ], 3),
  ...group("testing", "Junior", [1, 2, 4, 1, 2, 4], [
    ["What sequence describes the Arrange-Act-Assert test pattern?", ["Prepare inputs, execute behavior, verify the outcome", "Deploy, monitor, delete", "Compile, commit, merge", "Log, retry, ignore"], [0], "Arrange prepares the scenario, Act invokes the behavior, and Assert checks the observable result.", "testing"],
    ["Which cases are especially useful around a numeric input boundary? Select all that apply.", ["A value just below the boundary", "A value exactly on the boundary", "A value just above the boundary", "Only an unrelated random string"], [0, 1, 2], "Values immediately around a boundary reveal off-by-one and comparison errors.", "testing"],
    ["Why use a disposable real database in a repository integration test?", ["It exercises mappings, SQL, and constraints that mocks can miss", "It makes assertions unnecessary", "It guarantees production has no incidents", "It replaces unit tests"], [0], "A representative database checks the persistence boundary while isolation keeps tests repeatable.", "testing"],
    ["A test depends on the current time. How can you make it deterministic?", ["Inject a controllable clock", "Add a random sleep", "Run it only at midnight", "Remove its assertions"], [0], "A controllable clock lets the test fix time and verify time-dependent behavior repeatably.", "testing"],
    ["What should a service contract test verify?", ["The observable request and response agreement at the boundary", "Private variable names", "The developer's editor theme", "Only that the process starts"], [0], "Contract tests protect the interface consumers depend on, including shapes, status codes, and semantics.", "testing"],
    ["An AI feature can phrase correct answers differently. What is a robust automated check?", ["Evaluate required facts, schema, and safety constraints", "Require one exact paragraph for every valid answer", "Accept every non-empty response", "Check only token count"], [0], "Behavioral criteria and structured constraints are more stable than exact wording while still detecting failures.", "evaluation", "responsible-ai"],
  ], 3),
  ...group("tools", "Junior", [1, 2, 4, 1, 2, 4], [
    ["Why create a Git branch for a change?", ["To isolate a line of work from the main branch", "To erase repository history", "To install the JDK", "To encrypt environment variables"], [0], "A branch provides a separate movable line of development that can later be reviewed and merged.", "git", "git"],
    ["What does the Maven test phase normally do?", ["Compile and run the project's unit tests", "Deploy directly to production", "Delete source files", "Rotate production secrets"], [0], "The test phase compiles and runs tests through the configured test tooling.", "maven", "build-tools"],
    ["Where should a CI workflow obtain a production credential?", ["From the platform's protected secret store", "From a committed source file", "From a public build log", "From the README"], [0], "CI secrets should be injected through protected secret management and kept out of source and logs.", "ci", "ci-cd"],
    ["What does git status help you inspect?", ["The branch and the state of tracked, staged, and untracked files", "CPU temperature", "Database query plans", "Kubernetes Pod readiness"], [0], "git status summarizes the working tree and staging area before a commit.", "git", "git"],
    ["Why inspect git diff --staged before committing?", ["To review the exact patch that will enter the commit", "To publish the commit automatically", "To delete ignored files", "To change remote permissions"], [0], "The staged diff is the content currently selected for the next commit.", "git", "git"],
    ["What improves build reproducibility?", ["Pinning declared tool and dependency versions", "Downloading arbitrary latest versions during every build", "Skipping the test phase", "Editing artifacts after deployment"], [0], "Controlled versions make the same source more likely to produce the same tested artifact.", "maven", "build-tools"],
  ], 3),
  ...group("security", "Mid", [2, 4, 7, 2, 4, 7], [
    ["How should an application store user passwords?", ["As salted hashes using a password-specific algorithm", "As plain text", "As reversible values next to the encryption key", "Inside access logs"], [0], "Password-specific hashing with a unique salt limits damage and supports secure verification without storing the password.", "security"],
    ["Why must server-side validation remain even when the UI validates input?", ["Clients can bypass or alter UI checks", "The browser is always trusted", "It replaces authorization", "It makes HTTPS optional"], [0], "Requests can be crafted outside the UI, so the server must enforce its own input rules.", "security"],
    ["What benefit does method-level authorization add behind an authenticated controller?", ["It protects sensitive operations even when they are reached through another path", "It makes every caller an administrator", "It disables object ownership checks", "It stores passwords securely"], [0], "Authorization close to the operation provides defense in depth across different entry paths.", "security"],
    ["What does TLS primarily protect for an API connection?", ["Data confidentiality and integrity in transit", "Database backups at rest", "Authorization rules inside the service", "Correctness of business calculations"], [0], "TLS protects traffic against reading and tampering while it travels between endpoints.", "security"],
    ["Why are cookie-authenticated state-changing requests commonly protected against CSRF?", ["A browser may attach the user's cookie to a request initiated by another site", "Cookies cannot carry session identifiers", "CSRF only affects static files", "TLS rejects every cross-site request"], [0], "CSRF defenses prevent another origin from exploiting ambient browser credentials for an unwanted action.", "security"],
    ["An API accepts a list of record IDs for a bulk update. What authorization is required?", ["Permission must be checked for every affected record or an equivalent authorized scope", "Checking only the first ID", "Trusting IDs hidden by the UI", "Authentication without any resource check"], [0], "Bulk operations must enforce object-level authorization across the entire requested set.", "security"],
  ], 3),
  ...group("delivery", "Mid", [2, 4, 7, 2, 4, 7], [
    ["What should a readiness check answer?", ["Whether this instance can currently serve traffic", "Whether the source repository is public", "Whether every dependency is free", "Whether the image has the latest tag"], [0], "Readiness is a traffic-routing signal for the current instance.", "k8s"],
    ["Why deploy a container image by immutable digest?", ["It identifies the exact artifact that was tested", "It makes the image smaller", "It removes the registry", "It automatically migrates the database"], [0], "A digest pins the exact image content and avoids a mutable tag resolving to something different.", "docker"],
    ["Which signals should guide a canary rollout? Select all that apply.", ["Error rate", "Latency", "Key business outcomes", "Only the deployment name"], [0, 1, 2], "A canary should be compared using technical health and meaningful user outcomes before wider rollout.", "ci", "ci-cd"],
    ["What is a benefit of a multi-stage Docker build?", ["The runtime image can omit build-only tools and files", "It runs every stage in production", "It removes dependency versions", "It stores secrets in image layers safely"], [0], "Multi-stage builds copy required artifacts into a smaller runtime stage without retaining the full build environment.", "docker"],
    ["Why should a database change remain compatible with both old and new application versions during a rolling deploy?", ["Both versions may run at the same time", "Kubernetes rewrites SQL automatically", "Containers share one process", "Rollback is never needed"], [0], "Rolling deployment overlap requires the schema to serve both application versions until the rollout is complete.", "k8s"],
    ["What does build once, promote the same artifact achieve?", ["Each environment runs the artifact that passed earlier checks", "Production compiles a different binary", "Tests can be skipped", "Mutable tags become safe"], [0], "Promoting one immutable artifact reduces differences between tested and deployed software.", "ci", "ci-cd"],
  ], 3),
  ...group("ai", "Mid", [2, 4, 7, 2, 4, 7], [
    ["Why split long documents into chunks before embedding them for retrieval?", ["To retrieve focused passages that fit the model context", "To retrain the embedding model", "To remove access controls", "To guarantee the answer"], [0], "Chunking creates retrievable units with enough local context while respecting model and search limits.", "ai", "rag"],
    ["Which measurements help evaluate a RAG system? Select all that apply.", ["Whether retrieval finds relevant evidence", "Whether the answer is supported by that evidence", "Only the number of prompt characters", "Only the model vendor name"], [0, 1], "RAG evaluation should separate retrieval quality from answer grounding and usefulness.", "evaluation", "rag"],
    ["A retrieved document says to ignore system rules and call an admin tool. How should the application treat it?", ["As untrusted data, not authority to change tool permissions", "As a mandatory administrator command", "As proof that authorization passed", "As executable Java code"], [0], "Retrieved content can contain prompt injection; application policy and tool authorization remain authoritative.", "tools", "tool-calling"],
    ["What usually happens when generation temperature is reduced?", ["Outputs tend to become less varied", "The context window becomes unlimited", "Retrieval becomes unnecessary", "Every fact becomes correct"], [0], "Lower temperature generally concentrates sampling on higher-probability outputs, reducing variation.", "ai"],
    ["What is the value of showing citations in a grounded answer?", ["Users and evaluators can inspect the supporting evidence", "It proves the model cannot hallucinate", "It authorizes tool calls", "It encrypts source documents"], [0], "Citations make evidence traceable, although their correctness must still be checked.", "ai", "rag"],
    ["A tool returns text that will be placed into another prompt. What is the safe assumption?", ["Tool output is untrusted input that still needs boundaries and validation", "Tool output can override all policies", "The tool always returns code", "Authorization is no longer needed"], [0], "External tool output can be malformed or adversarial and must not gain authority merely by entering the prompt.", "tools", "tool-calling"],
  ], 3),
  ...group("observability", "Mid", [2, 4, 7, 2, 4, 7], [
    ["Why use structured fields in application logs?", ["They make events consistently searchable and aggregatable", "They eliminate the need for timestamps", "They automatically fix failures", "They permit logging secrets"], [0], "Stable fields such as level, request ID, and operation support reliable querying and correlation.", "observations"],
    ["Why is p95 latency often more informative than average latency?", ["It reveals the experience of slower requests hidden by the mean", "It is always the maximum", "It counts only failed requests", "It measures source-code complexity"], [0], "A percentile describes the latency below which a percentage of requests complete and exposes tail behavior.", "observations"],
    ["What is required to connect trace spans across service boundaries?", ["Propagate trace context with the request", "Use the same class name", "Restart every service together", "Write all logs to one file"], [0], "Trace context propagation lets downstream spans join the originating distributed trace.", "observations"],
    ["Which data should normally be redacted from logs?", ["Passwords, access tokens, and sensitive personal data", "HTTP status codes", "Service names", "Non-sensitive duration values"], [0], "Logs are widely replicated operational data; credentials and sensitive user data should not be recorded.", "observations"],
    ["What makes an alert actionable?", ["It identifies a user-impacting symptom with an owner and response path", "It fires for every debug message", "It has no threshold", "It measures only server uptime"], [0], "An actionable alert is tied to meaningful impact and a response the on-call engineer can take.", "observations"],
    ["Why is user_id usually a poor metric label?", ["Its unbounded cardinality can make the metric system expensive and unstable", "Metrics cannot contain labels", "User IDs are always numbers", "It prevents logs from being written"], [0], "A label value per user creates an unbounded time-series set; keep such identifiers in controlled logs or traces instead.", "observations"],
  ], 3),
  ...group("concurrency", "Senior", [3, 6, 9, 3, 6, 9], [
    ["Several threads increment one counter. What is needed to avoid lost updates?", ["An atomic operation or appropriate synchronization", "A longer variable name", "A random sleep", "A local copy in every method"], [0], "A read-modify-write increment must be atomic or protected so concurrent updates are not overwritten.", "threads", "multithreading"],
    ["Why bound the queue of an executor that serves requests?", ["To apply backpressure instead of allowing unbounded memory growth", "To make every task synchronous", "To disable rejection handling", "To guarantee zero latency"], [0], "A bounded queue limits accumulated work and makes overload behavior explicit.", "threads", "multithreading"],
    ["A virtual-thread service calls a dependency that accepts only 50 concurrent requests. What should the service do?", ["Bound concurrency to the dependency despite cheap virtual threads", "Start unlimited calls", "Remove timeouts", "Convert every call to CPU work"], [0], "Virtual threads make waiting cheaper but do not increase downstream capacity.", "virtual"],
    ["What guarantee does volatile provide for a Java field?", ["Visibility and ordering for reads and writes of that field", "Atomicity for every compound operation", "Mutual exclusion for an entire object", "Deadlock prevention"], [0], "volatile establishes visibility and ordering guarantees, but operations such as increment remain compound.", "threads", "multithreading"],
    ["How can code reduce deadlock risk when it must acquire multiple locks?", ["Acquire locks in a consistent global order", "Add longer sleeps", "Use a different order in every thread", "Ignore interruption"], [0], "A consistent lock order prevents the circular wait pattern required for deadlock.", "threads", "multithreading"],
    ["In a group of related concurrent subtasks, what should happen when one required subtask fails?", ["Cancel or contain sibling work according to the operation's policy", "Let every task run forever", "Hide the failure", "Restart the JVM immediately"], [0], "Related task lifetimes should be bounded so failure does not leave orphaned work consuming resources.", "threads", "multithreading"],
  ], 3),
  ...group("distributed", "Senior", [3, 6, 10, 3, 6, 10], [
    ["Why choose a stable business key as the Kafka partition key?", ["Events for that key can retain partition-local order", "It creates a global order across all partitions", "It prevents every duplicate", "It encrypts the payload"], [0], "Kafka preserves order within a partition, so a stable key co-locates related events in that ordering boundary.", "kafka"],
    ["When should a consumer commit an offset relative to a required database update?", ["Only after the processing outcome is durably handled according to the delivery design", "Before reading the message", "Randomly", "Only when the process shuts down"], [0], "Offset and side-effect ordering determines whether failure produces loss or replay; the design must make replay safe.", "kafka"],
    ["What should an idempotency record store for a retried command?", ["A stable request key and the durable outcome or processing state", "Only the current timestamp", "A random partition on every retry", "The caller's password"], [0], "A stable key lets the service recognize a retry and return or complete the original outcome without repeating the effect.", "kafka", "idempotency"],
    ["A network timeout occurs after sending a write. What must the caller assume?", ["The outcome may be unknown and a retry can duplicate the effect", "The write definitely failed", "The write definitely succeeded", "The network rolled back the remote database"], [0], "A timeout hides the remote outcome; safe retries require idempotency or reconciliation.", "retry"],
    ["Can a transactional outbox guarantee exactly-once delivery to every external consumer?", ["No; relaying can repeat, so consumers still need duplicate handling", "Yes, for every external system", "Yes, if the table has no index", "No, because it cannot store events"], [0], "The outbox makes the local state change and event record atomic, but publication can be retried.", "outbox", "outbox"],
    ["What is backpressure in an event pipeline?", ["A way for limited consumers to constrain or signal upstream production", "An instruction to drop all messages", "A global transaction across every service", "A replacement for monitoring"], [0], "Backpressure prevents an overloaded consumer from being buried under unbounded queued work.", "kafka"],
  ], 3),
  ...group("performance", "Senior", [3, 6, 9, 3, 6, 9], [
    ["A heap keeps growing even after requests complete. What should you inspect?", ["Which objects remain reachable and what retains them", "Only source-file size", "The number of Git branches", "The container image name"], [0], "A heap dump and retention paths can reveal references that keep objects alive unexpectedly.", "jfr", "jvm"],
    ["Why does a reliable JVM microbenchmark include warm-up?", ["To reduce distortion from class loading and JIT compilation", "To increase network latency", "To disable garbage collection", "To make assertions unnecessary"], [0], "Warm-up lets the runtime reach a representative optimized state before measurement.", "jfr", "jvm"],
    ["What is a cache stampede?", ["Many callers concurrently recompute the same expired value", "A cache with no keys", "A database transaction rollback", "A JVM syntax error"], [0], "When a hot entry expires, simultaneous misses can overwhelm the backing dependency unless refresh work is coordinated.", "cache"],
    ["A service has high latency but low CPU. Which artifact can expose threads waiting on locks or I/O?", ["A thread dump or recording", "A README badge", "A Git tag", "A database primary key"], [0], "Thread states and stack traces show whether work is blocked, waiting, or running.", "jfr", "jvm"],
    ["Why track allocation rate as well as heap size?", ["High short-lived allocation can create GC pressure without a large steady heap", "Allocation rate is the same as request count", "Heap size includes disk usage", "GC ignores newly allocated objects"], [0], "Rapid temporary allocation can consume memory bandwidth and trigger frequent collections.", "gc", "garbage-collector"],
    ["What makes a load test useful for a planned production change?", ["Representative traffic, data, dependencies, and explicit success criteria", "Maximum traffic with no measurements", "A single request on a laptop", "Random JVM flags applied during the run"], [0], "A representative workload and defined latency, error, and resource targets make results actionable.", "jfr", "jvm"],
  ], 3),
  ...group("operations", "Senior", [3, 6, 9, 3, 6, 9], [
    ["What is the difference between a Kubernetes resource request and limit?", ["The request guides scheduling; the limit caps allowed resource use", "They are two names for a Pod", "The request is always larger", "The limit controls Git permissions"], [0], "Schedulers use requests for placement, while limits constrain runtime resource consumption.", "k8s"],
    ["What does a rolling deployment aim to do?", ["Replace instances gradually while maintaining service capacity", "Stop every instance before starting any new one", "Rewrite the database automatically", "Disable readiness checks"], [0], "A rolling update introduces the new version in steps and removes old instances as replacements become ready.", "k8s"],
    ["Which failure belongs in a liveness probe rather than readiness?", ["A local process is irrecoverably stuck and needs restart", "A dependency is briefly slow", "The instance is warming a cache", "A rollout has not reached full capacity"], [0], "Liveness should detect local states that restarting the container can actually repair.", "k8s"],
    ["Why implement graceful shutdown in an API Pod?", ["To stop new work and allow in-flight requests to finish within a bound", "To ignore termination signals", "To keep the Pod ready forever", "To delete persistent data"], [0], "Graceful shutdown coordinates traffic removal and bounded completion before process exit.", "k8s"],
    ["What can a PodDisruptionBudget protect against?", ["Too many voluntary Pod disruptions at the same time", "Every node hardware failure", "Application data corruption", "Invalid container images"], [0], "A disruption budget constrains voluntary evictions; it is not a guarantee against all outages.", "k8s"],
    ["When is a circuit breaker useful?", ["To stop repeated calls to a failing dependency and allow controlled recovery", "To retry every request forever", "To replace authorization", "To increase metric cardinality"], [0], "A circuit breaker fails fast during sustained dependency failure and probes recovery after a bounded interval.", "retry"],
  ], 3),
  ...group("agents", "Senior", [3, 6, 10, 3, 6, 10], [
    ["Why keep final evaluation cases separate from prompt development examples?", ["To reduce overfitting and preserve an honest quality estimate", "To make the model see every answer", "To eliminate human review", "To increase context length"], [0], "A held-out set tests whether improvements generalize beyond cases used during development.", "evaluation"],
    ["Which tool action most clearly needs human approval in a coding agent?", ["Irreversibly deleting production customer data", "Reading a public API description", "Formatting a local temporary file", "Calculating a checksum"], [0], "High-impact irreversible actions should cross an explicit human approval boundary.", "tools", "tool-calling"],
    ["What should drive model routing between a small and large model?", ["Measured task risk, quality, latency, and cost requirements", "A random choice", "Only model name length", "Always selecting the most expensive option"], [0], "Routing should be validated against representative task outcomes and operational constraints.", "evaluation"],
    ["Before executing a model-proposed tool call, what must the host validate? Select all that apply.", ["The tool is allowed for this user and task", "Arguments satisfy the tool schema and policy", "The text sounds confident", "The model used many tokens"], [0, 1], "The host application owns authorization and schema validation regardless of how the call was proposed.", "tools", "tool-calling"],
    ["Why evaluate an agent's full trajectory instead of only its final text?", ["Unsafe or wasteful tool actions can occur even when the final answer looks acceptable", "Intermediate steps never affect systems", "Only token count matters", "Tools cannot fail"], [0], "Trajectory evaluation exposes unnecessary calls, policy violations, and recovery behavior hidden by the final message.", "evaluation"],
    ["What is a safe default for long-term agent memory containing user data?", ["Store only necessary scoped data with retention and deletion controls", "Keep every interaction forever", "Share memory across unrelated users", "Put secrets into prompts by default"], [0], "Memory should follow data minimization, tenant isolation, explicit retention, and deletion policy.", "tools", "tool-calling"],
  ], 3),
];
