"""file and secret security

Revision ID: 20260824_0004
Revises: 20260824_0003
Create Date: 2026-08-24 11:41:46.196205
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260824_0004"
down_revision: str | None = "20260824_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM processor_usages)
               OR EXISTS (
                   SELECT 1 FROM processor_deletion_tasks
                   WHERE processor_subject_reference IS NOT NULL
               ) THEN
                RAISE EXCEPTION
                    'Phase 0C-C requires processor locators to be cleared before migration';
            END IF;
        END;
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parser_release_policies",
        sa.Column("policy_key", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("privacy_policy_version_id", sa.UUID(), nullable=False),
        sa.Column("data_category", sa.String(length=100), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("maximum_bytes", sa.Integer(), nullable=False),
        sa.Column("malware_scan_required", sa.Boolean(), nullable=False),
        sa.Column("parser_adapter", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("isolation_profile", sa.String(length=100), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(isolation_profile) <> ''",
            name=op.f("ck_parser_release_policies_isolation_profile_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(parser_adapter) <> ''",
            name=op.f("ck_parser_release_policies_parser_adapter_nonempty"),
        ),
        sa.CheckConstraint(
            "btrim(parser_version) <> ''",
            name=op.f("ck_parser_release_policies_parser_version_nonempty"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'retired')",
            name=op.f("ck_parser_release_policies_status_allowed"),
        ),
        sa.CheckConstraint(
            "maximum_bytes >= 1024", name=op.f("ck_parser_release_policies_maximum_bytes_positive")
        ),
        sa.ForeignKeyConstraint(
            ["privacy_policy_version_id"],
            ["privacy_policy_versions.id"],
            name=op.f(
                "fk_parser_release_policies_privacy_policy_version_id_privacy_policy_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parser_release_policies")),
        sa.UniqueConstraint("policy_key", "policy_version", name="uq_parser_policy_key_version"),
    )
    op.create_index(
        "ix_parser_release_policies_resolution",
        "parser_release_policies",
        ["privacy_policy_version_id", "data_category", "purpose", "media_type", "status"],
        unique=False,
    )
    op.create_table(
        "file_assets",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("privacy_policy_version_id", sa.UUID(), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=False),
        sa.Column("data_category", sa.String(length=100), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("quarantine_object_key", sa.String(length=512), nullable=False),
        sa.Column("quarantine_version_id", sa.String(length=1024), nullable=True),
        sa.Column("released_object_key", sa.String(length=512), nullable=True),
        sa.Column("released_version_id", sa.String(length=1024), nullable=True),
        sa.Column("kms_key_id", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("content_length", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_release_policy_id", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retention_action", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "retention_action IN ('delete', 'anonymize')",
            name=op.f("ck_file_assets_retention_action_allowed"),
        ),
        sa.CheckConstraint(
            "status <> 'released' OR (released_object_key IS NOT NULL AND "
            "released_version_id IS NOT NULL AND parser_release_policy_id IS NOT NULL)",
            name=op.f("ck_file_assets_released_state_complete"),
        ),
        sa.CheckConstraint(
            "status IN ('upload_pending', 'deletion_pending') OR quarantine_version_id IS NOT NULL",
            name=op.f("ck_file_assets_uploaded_state_requires_version"),
        ),
        sa.CheckConstraint(
            "status IN ('upload_pending', 'quarantined', 'scan_failed', 'clean', "
            "'released', 'deletion_pending')",
            name=op.f("ck_file_assets_status_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(content_sha256) = 64", name=op.f("ck_file_assets_content_digest_length")
        ),
        sa.CheckConstraint(
            "content_length >= 1", name=op.f("ck_file_assets_content_length_positive")
        ),
        sa.CheckConstraint(
            "retain_until > created_at", name=op.f("ck_file_assets_retention_after_creation")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_file_assets_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parser_release_policy_id"],
            ["parser_release_policies.id"],
            name=op.f("fk_file_assets_parser_release_policy_id_parser_release_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["privacy_policy_version_id"],
            ["privacy_policy_versions.id"],
            name=op.f("fk_file_assets_privacy_policy_version_id_privacy_policy_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_assets")),
        sa.UniqueConstraint("bucket", "quarantine_object_key", name="uq_file_asset_quarantine_key"),
    )
    op.create_index(
        "ix_file_assets_owner_created", "file_assets", ["account_id", "created_at"], unique=False
    )
    op.create_index("ix_file_assets_retention", "file_assets", ["retain_until"], unique=False)
    op.create_index(
        "ix_file_assets_status_updated", "file_assets", ["status", "updated_at"], unique=False
    )
    op.create_table(
        "file_deletion_tasks",
        sa.Column("file_asset_id", sa.UUID(), nullable=True),
        sa.Column("privacy_request_id", sa.UUID(), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("task_kind", sa.String(length=24), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("quarantine_object_key", sa.String(length=512), nullable=True),
        sa.Column("released_object_key", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retention_action", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "retention_action IN ('delete', 'anonymize')",
            name=op.f("ck_file_deletion_tasks_retention_action_allowed"),
        ),
        sa.CheckConstraint(
            "status = 'completed' OR quarantine_object_key IS NOT NULL OR "
            "released_object_key IS NOT NULL",
            name=op.f("ck_file_deletion_tasks_active_task_requires_object_key"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'retry', 'escalated', 'completed')",
            name=op.f("ck_file_deletion_tasks_status_allowed"),
        ),
        sa.CheckConstraint(
            "task_kind IN ('quarantine_cleanup', 'asset_deletion')",
            name=op.f("ck_file_deletion_tasks_task_kind_allowed"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_file_deletion_tasks_attempts_nonnegative")
        ),
        sa.CheckConstraint(
            "retain_until > created_at",
            name=op.f("ck_file_deletion_tasks_retention_after_creation"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_file_deletion_tasks_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["file_assets.id"],
            name=op.f("fk_file_deletion_tasks_file_asset_id_file_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_deletion_tasks")),
        sa.UniqueConstraint("file_asset_id", "task_kind", name="uq_file_deletion_task_asset_kind"),
    )
    op.create_index(
        "ix_file_deletion_tasks_available",
        "file_deletion_tasks",
        ["status", "available_at"],
        unique=False,
    )
    op.create_index(
        "ix_file_deletion_tasks_request",
        "file_deletion_tasks",
        ["privacy_request_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_file_deletion_tasks_retention", "file_deletion_tasks", ["retain_until"], unique=False
    )
    op.create_table(
        "file_scan_attempts",
        sa.Column("file_asset_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scanner_engine_version", sa.String(length=64), nullable=True),
        sa.Column("scanner_signature_version", sa.String(length=64), nullable=True),
        sa.Column("scanner_signature_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("malware_signature_sha256", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "scanned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'error' AND error_code IS NOT NULL) OR "
            "(status <> 'error' AND error_code IS NULL)",
            name=op.f("ck_file_scan_attempts_error_state_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('clean', 'infected', 'error')",
            name=op.f("ck_file_scan_attempts_status_allowed"),
        ),
        sa.CheckConstraint(
            "attempt_number >= 1", name=op.f("ck_file_scan_attempts_attempt_number_positive")
        ),
        sa.CheckConstraint(
            "malware_signature_sha256 IS NULL OR char_length(malware_signature_sha256) = 64",
            name=op.f("ck_file_scan_attempts_malware_digest_length"),
        ),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["file_assets.id"],
            name=op.f("fk_file_scan_attempts_file_asset_id_file_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_scan_attempts")),
        sa.UniqueConstraint("file_asset_id", "attempt_number", name="uq_file_scan_attempt_number"),
    )
    op.create_index(
        "ix_file_scan_attempts_asset_scanned",
        "file_scan_attempts",
        ["file_asset_id", "scanned_at"],
        unique=False,
    )
    op.add_column(
        "backup_deletion_markers",
        sa.Column(
            "subject_key_id",
            sa.String(length=64),
            server_default=sa.text("'legacy-v1'"),
            nullable=False,
        ),
    )
    op.add_column(
        "processor_deletion_tasks",
        sa.Column("processor_subject_ciphertext", sa.LargeBinary(), nullable=True),
    )
    op.add_column(
        "processor_deletion_tasks",
        sa.Column("processor_subject_nonce", sa.LargeBinary(length=12), nullable=True),
    )
    op.add_column(
        "processor_deletion_tasks",
        sa.Column("processor_subject_key_id", sa.String(length=64), nullable=True),
    )
    op.drop_constraint(
        op.f("ck_processor_deletion_tasks_active_task_requires_locator"),
        "processor_deletion_tasks",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_processor_deletion_tasks_active_task_requires_locator"),
        "processor_deletion_tasks",
        "status NOT IN ('pending', 'processing', 'retry') OR "
        "processor_subject_reference IS NOT NULL OR processor_subject_ciphertext IS NOT NULL",
    )
    op.create_check_constraint(
        op.f("ck_processor_deletion_tasks_encrypted_locator_complete"),
        "processor_deletion_tasks",
        "processor_subject_ciphertext IS NULL OR (processor_subject_nonce IS NOT NULL "
        "AND processor_subject_key_id IS NOT NULL)",
    )
    op.add_column(
        "processor_usages",
        sa.Column("processor_subject_ciphertext", sa.LargeBinary(), nullable=True),
    )
    op.add_column(
        "processor_usages",
        sa.Column("processor_subject_nonce", sa.LargeBinary(length=12), nullable=True),
    )
    op.add_column(
        "processor_usages",
        sa.Column("processor_subject_key_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "processor_usages",
        sa.Column("processor_subject_digest", sa.String(length=64), nullable=False),
    )
    op.alter_column(
        "processor_usages",
        "processor_subject_reference",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_constraint(op.f("uq_processor_usage_locator"), "processor_usages", type_="unique")
    op.create_unique_constraint(
        "uq_processor_usage_locator",
        "processor_usages",
        ["account_id", "processor_activity_id", "processor_subject_digest"],
    )
    op.create_check_constraint(
        op.f("ck_processor_usages_locator_digest_length"),
        "processor_usages",
        "char_length(processor_subject_digest) = 64",
    )
    op.create_check_constraint(
        op.f("ck_processor_usages_locator_representation_complete"),
        "processor_usages",
        "(processor_subject_reference IS NOT NULL AND processor_subject_ciphertext IS NULL "
        "AND processor_subject_nonce IS NULL AND processor_subject_key_id IS NULL) OR "
        "(processor_subject_reference IS NULL AND processor_subject_ciphertext IS NOT NULL "
        "AND processor_subject_nonce IS NOT NULL AND processor_subject_key_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM processor_usages
                WHERE processor_subject_reference IS NULL
            ) OR EXISTS (
                SELECT 1 FROM processor_deletion_tasks
                WHERE processor_subject_ciphertext IS NOT NULL
            ) THEN
                RAISE EXCEPTION
                    'Cannot downgrade while encrypted processor locators exist';
            END IF;
        END;
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_processor_usages_locator_representation_complete"),
        "processor_usages",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_processor_usages_locator_digest_length"), "processor_usages", type_="check"
    )
    op.drop_constraint("uq_processor_usage_locator", "processor_usages", type_="unique")
    op.create_unique_constraint(
        op.f("uq_processor_usage_locator"),
        "processor_usages",
        ["account_id", "processor_activity_id", "processor_subject_reference"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "processor_usages",
        "processor_subject_reference",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("processor_usages", "processor_subject_digest")
    op.drop_column("processor_usages", "processor_subject_key_id")
    op.drop_column("processor_usages", "processor_subject_nonce")
    op.drop_column("processor_usages", "processor_subject_ciphertext")
    op.drop_constraint(
        op.f("ck_processor_deletion_tasks_encrypted_locator_complete"),
        "processor_deletion_tasks",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_processor_deletion_tasks_active_task_requires_locator"),
        "processor_deletion_tasks",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_processor_deletion_tasks_active_task_requires_locator"),
        "processor_deletion_tasks",
        "status NOT IN ('pending', 'processing', 'retry') OR "
        "processor_subject_reference IS NOT NULL",
    )
    op.drop_column("processor_deletion_tasks", "processor_subject_key_id")
    op.drop_column("processor_deletion_tasks", "processor_subject_nonce")
    op.drop_column("processor_deletion_tasks", "processor_subject_ciphertext")
    op.drop_column("backup_deletion_markers", "subject_key_id")
    op.drop_index("ix_file_scan_attempts_asset_scanned", table_name="file_scan_attempts")
    op.drop_table("file_scan_attempts")
    op.drop_index("ix_file_deletion_tasks_retention", table_name="file_deletion_tasks")
    op.drop_index("ix_file_deletion_tasks_request", table_name="file_deletion_tasks")
    op.drop_index("ix_file_deletion_tasks_available", table_name="file_deletion_tasks")
    op.drop_table("file_deletion_tasks")
    op.drop_index("ix_file_assets_status_updated", table_name="file_assets")
    op.drop_index("ix_file_assets_retention", table_name="file_assets")
    op.drop_index("ix_file_assets_owner_created", table_name="file_assets")
    op.drop_table("file_assets")
    op.drop_index("ix_parser_release_policies_resolution", table_name="parser_release_policies")
    op.drop_table("parser_release_policies")
    # ### end Alembic commands ###
