import type {
  InterviewLanguage,
  InterviewStage,
  QuestionCategory,
  QuestionSource,
  Seniority,
} from "./interview-api";

export type UiLanguage = "en" | "az";

const englishStageLabels: Record<InterviewStage, string> = {
  "Not sure": "Not sure",
  "HR / Recruiter": "HR / Recruiter",
  "Technical Interview": "Technical Interview",
  "Coding Interview": "Coding Interview",
  "System Design": "System Design",
  "Hiring Manager": "Hiring Manager",
  "Final Interview": "Final Interview",
};

const azerbaijaniStageLabels: Record<InterviewStage, string> = {
  "Not sure": "Əmin deyiləm",
  "HR / Recruiter": "HR / Rekruter",
  "Technical Interview": "Texniki müsahibə",
  "Coding Interview": "Kodlaşdırma müsahibəsi",
  "System Design": "Sistem dizaynı",
  "Hiring Manager": "İşə qəbul meneceri",
  "Final Interview": "Yekun müsahibə",
};

const englishSeniorityLabels: Record<Seniority, string> = {
  "Not specified": "Not specified",
  Intern: "Intern",
  Junior: "Junior",
  "Mid-level": "Mid-level",
  Senior: "Senior",
  Lead: "Lead",
};

const azerbaijaniSeniorityLabels: Record<Seniority, string> = {
  "Not specified": "Qeyd edilməyib",
  Intern: "Təcrübəçi",
  Junior: "Başlanğıc",
  "Mid-level": "Orta səviyyə",
  Senior: "Baş mütəxəssis",
  Lead: "Rəhbər",
};

const englishCategoryLabels: Record<QuestionCategory, string> = {
  "HR / Recruiter": "HR / Recruiter",
  "CV Questions": "CV Questions",
  "Technical Questions": "Technical Questions",
  "System Design": "System Design",
};

const azerbaijaniCategoryLabels: Record<QuestionCategory, string> = {
  "HR / Recruiter": "HR / Rekruter",
  "CV Questions": "CV sualları",
  "Technical Questions": "Texniki suallar",
  "System Design": "Sistem dizaynı",
};

const englishSourceLabels: Record<QuestionSource, string> = {
  Company: "Company",
  "Job Description": "Job Description",
  CV: "CV",
  Role: "Role",
  Industry: "Industry",
  "Interview Pattern": "Interview Pattern",
};

const azerbaijaniSourceLabels: Record<QuestionSource, string> = {
  Company: "Şirkət",
  "Job Description": "Vakansiya təsviri",
  CV: "CV",
  Role: "Vəzifə",
  Industry: "Sahə",
  "Interview Pattern": "Müsahibə nümunəsi",
};

const englishInterviewLanguageLabels: Record<InterviewLanguage, string> = {
  English: "English",
  Azerbaijani: "Azerbaijani",
};

const azerbaijaniInterviewLanguageLabels: Record<InterviewLanguage, string> = {
  English: "İngilis dili",
  Azerbaijani: "Azərbaycan dili",
};

export const uiCopy = {
  en: {
    localeName: "English",
    switchLanguage: "Interface language",
    brandAria: "Interview Prep home",
    nav: { label: "Interview preparation", overview: "Overview", questions: "Questions", practice: "Practice", newPreparation: "New preparation" },
    home: {
      eyebrow: "Interview preparation",
      title: "Prepare for the interview you're actually going to have.",
      intro: "Paste the vacancy, tell us the company and role, and optionally add your CV. We'll identify the questions worth preparing and let you practise them in a realistic interview.",
      cta: "Prepare for an Interview",
      noAccount: "No account required for this product preview.",
      previewAria: "Example interview preparation result",
      previewLabel: "Interview preparation",
      previewCompany: "PASHA Bank",
      previewRole: "AI Engineer",
      previewStage: "Technical Interview",
      sources: "Preparation sources",
      included: "Included",
      available: "Available",
      jobRequirements: "Job requirements",
      companySignals: "Company signals",
      focusAreas: "Likely focus areas",
      rag: "RAG & LLM Systems",
      python: "Python",
      ml: "ML Fundamentals",
      deployment: "Deployment",
      high: "High",
      medium: "Medium",
      questionCount: "34 likely questions",
      exampleQuestionLabel: "Example question",
      exampleQuestion: "How would you evaluate retrieval quality independently from the final LLM response?",
      jobDescription: "Job Description",
      onePreparation: "One preparation",
      benefitsTitle: "What you get from one preparation",
      benefitsIntro: "One setup gives you both a focused question set and a realistic interview practice session.",
      benefits: [
        ["Questions tailored to the vacancy", "The role requirements are broken into the areas an interviewer is most likely to test."],
        ["Questions from your CV", "Projects, technologies and claims in your CV become realistic interviewer follow-ups."],
        ["Practice the interview", "Answer selected questions and continue with follow-ups based on your responses."],
      ],
      personalised: "Personalised preparation",
      personalisedTitle: "Built around the interview you're applying for",
      personalisedIntro: "Vacancy requirements and CV evidence are connected before questions are selected.",
      vacancyTitle: "AI Engineer vacancy",
      vacancySignals: ["Python", "RAG", "LLM evaluation", "Docker", "Production ML"],
      cvSignalsTitle: "CV signals",
      cvSignals: ["Built a RAG platform", "Worked with FAISS", "Deployed using Docker"],
      likelyQuestions: "Likely questions",
      sampleQuestions: [
        "How did you evaluate your RAG retrieval?",
        "Why did you choose FAISS?",
        "How did you monitor the system in production?",
        "What failure cases did you encounter?",
      ],
      recent: "Recent",
      continuePreparing: "Continue preparing",
      ready: "Ready when you are",
      finalTitle: "Prepare for your interview.",
      finalIntro: "Add the role and vacancy. Your likely questions will be ready in one focused preparation.",
      start: "Start a Preparation",
      footer: "Focused preparation for specific roles and vacancies.",
    },
    form: {
      eyebrow: "New preparation",
      title: "Tell us what interview you're preparing for.",
      intro: "Complete the details below. It should take no more than a few minutes.",
      roleTitle: "Role details",
      roleIntro: "Start with the company and position.",
      company: "Company",
      role: "Role / Position",
      jobLink: "Job posting link",
      optional: "Optional",
      requirementsTitle: "Job requirements",
      requirementsIntro: "This is the strongest input for tailoring your questions.",
      jobDescription: "Job Description / Requirements",
      jobPlaceholder: "Paste the job description or vacancy requirements here...",
      characters: (count: number) => `${count} characters · minimum 40`,
      interviewTitle: "Interview details",
      interviewIntro: "Choose what you know. “Not sure” is completely fine.",
      seniority: "Seniority",
      stage: "Interview stage",
      language: "Interview language",
      cvTitle: "Add your CV",
      cvIntro: "Get questions based on the projects, technologies and claims in your CV.",
      readyToReview: "Ready to review",
      remove: "Remove",
      uploadStart: "Drag and drop your CV, or",
      chooseFile: "choose a file",
      uploadMeta: "PDF or DOCX · maximum 10 MB",
      cvExplanation: "Adding your CV helps us prepare questions interviewers may ask about your projects, skills and experience.",
      privacy: "We use these details only to prepare this interview.",
      prepare: "Prepare Interview",
      invalidFile: "Please choose a PDF or DOCX file.",
      fileTooLarge: "The CV must be smaller than 10 MB.",
      fileReadError: "We could not read this CV. Please choose the file again.",
      prepareError: "We could not prepare this interview. Please check the details and try again.",
    },
    analysis: {
      eyebrow: "Preparing your interview",
      title: (role: string) => `Building a focused preparation for ${role}.`,
      steps: ["Analyzing the role", "Reading job requirements", "Reviewing your CV", "Researching relevant interview signals", "Preparing likely questions"],
      noCv: "No CV added — continuing with role and vacancy evidence.",
    },
    preparation: {
      eyebrow: "Your interview preparation",
      coverageAria: "Company-specific data coverage",
      companyData: "Company-specific data",
      limited: "Limited",
      strong: "Strong",
      liveResearch: "Live research",
      localPreview: "Local preview",
      evidence: "Public evidence",
      sourcesUsed: (count: number) => `${count} research source${count === 1 ? "" : "s"} used`,
      companySignals: "Company research",
      companySignalsTitle: "Verified signals shaping these questions",
      companySignalsIntro: "Only public signals that could be linked to a source are included here.",
      previewNote: "Live company research is unavailable, so these questions use only vacancy and role patterns. They are not presented as company-specific.",
      limitedNote: "Public interview information for this company is limited. Questions are weighted more heavily toward the vacancy, role, industry and your CV.",
      strongNote: "Company-specific signals are available and are combined with the vacancy, role, industry and your CV.",
      likelyFocus: "Likely focus",
      explore: "What this interview may explore",
      focusIntro: "Based on the role, vacancy requirements and available evidence.",
      choose: "Choose how to prepare",
      ready: "Your questions are ready",
      viewQuestions: "View Questions",
      viewQuestionsIntro: "Review likely questions and why each one matters. You do not need to answer.",
      practiceInterview: "Practice Interview",
      practiceIntro: "Answer selected questions and receive realistic follow-ups.",
    },
    questions: {
      sheet: "Preparation sheet",
      title: "Likely Interview Questions",
      intro: "Selected from the role, job requirements, your CV and available interview signals.",
      cvReview: "CV review",
      cvAreas: "CV areas likely to be explored",
      noCv: "No CV added",
      noCvIntro: "Your questions are based on the vacancy, role, industry and interview stage. You can start a new preparation to add a CV.",
      filterAria: "Filter questions by category",
      all: "All questions",
      listAria: "Likely interview questions",
      why: "Why this question?",
      approach: "How should I approach this?",
      practice: "Practice",
      whyTitle: "Why it matters",
      approachTitle: "A strong answer should cover",
      evidence: "Evidence",
    },
    practice: {
      eyebrow: "Practice interview",
      title: "Choose how you want to practise.",
      intro: "Answer questions selected specifically for this interview and receive relevant follow-ups.",
      chooseMode: "Choose mode",
      real: "Real Interview",
      realIntro: "Feedback is provided at the end.",
      practice: "Practice",
      practiceIntro: "Receive feedback while practising.",
      focus: "Focus",
      duration: "Duration",
      focusLabels: { "Full Interview": "Full Interview", Technical: "Technical", "HR / Behavioral": "HR / Behavioral", "CV Deep Dive": "CV Deep Dive" },
      questionCount: (count: number) => `${count} tailored questions available`,
      start: "Start Interview",
      modeLabels: { "Real Interview": "Real Interview", Practice: "Practice" },
    },
    active: {
      end: "End Interview",
      questionProgress: (current: number, total: number) => `Question ${current} of ${total}`,
      interviewer: "Interviewer",
      selectedFrom: "Selected from",
      followUpTopic: "Follow-up based on this topic",
      answer: "Your answer",
      placeholder: "Write your answer as you would say it in the interview...",
      submit: "Submit Answer",
      feedback: "Practice feedback",
      feedbackTitle: "Strengthen the evidence in your answer.",
      strongPoints: "Strong points",
      strongItems: ["You gave enough context to follow your reasoning.", "Your answer addressed the core question directly."],
      improve: "Improve",
      improveItems: ["Make your personal contribution explicit.", "Add one measurable result or decision criterion."],
      likelyFollowUp: "Likely follow-up",
      continue: "Continue",
    },
    report: {
      complete: "Interview complete",
      title: "Your preparation has a clear next step.",
      summary: (completed: number, mode: string) => `You completed ${completed} question${completed === 1 ? "" : "s"} in ${mode.toLocaleLowerCase("en-US")} mode. Review the evidence behind each answer before your real interview.`,
      worked: "What worked",
      keep: "Keep doing this",
      workedItems: ["Address the question before adding background.", "Explain the reasoning behind technical choices.", "Connect your experience to the target role."],
      improve: "Improve next",
      credible: "Make each answer more credible",
      improveItems: ["Quantify outcomes wherever possible.", "Compare at least one realistic alternative.", "Clarify what you personally owned."],
      next: "Recommended next step",
      recommendation: "Review the likely questions and prepare two measurable examples.",
      viewQuestions: "View Questions",
      practiceAgain: "Practice Again",
    },
    stageLabels: englishStageLabels,
    seniorityLabels: englishSeniorityLabels,
    categoryLabels: englishCategoryLabels,
    sourceLabels: englishSourceLabels,
    interviewLanguageLabels: englishInterviewLanguageLabels,
    focusAreaLabels: { rag: "RAG / LLM systems", python: "Python and API engineering", deployment: "Production deployment", decisions: "Technical decision-making", evidence: "Clear evidence and outcomes", ownership: "Project ownership", technicalDecisions: "Technical decisions", outcomes: "Measured outcomes" },
    priorityLabels: { High: "High", Medium: "Medium" },
    specificityLabels: { "Company evidence": "Company evidence", Vacancy: "Vacancy evidence", "Role pattern": "Role pattern" },
  },
  az: {
    localeName: "Azərbaycan dili",
    switchLanguage: "İnterfeys dili",
    brandAria: "Müsahibəyə Hazırlıq ana səhifəsi",
    nav: { label: "Müsahibə hazırlığı", overview: "İcmal", questions: "Suallar", practice: "Praktika", newPreparation: "Yeni hazırlıq" },
    home: {
      eyebrow: "Müsahibəyə hazırlıq",
      title: "Sizi həqiqətən gözləyən müsahibəyə hazırlaşın.",
      intro: "Vakansiyanı əlavə edin, şirkət və vəzifəni qeyd edin, istəyinizə görə CV-nizi yükləyin. Hazırlaşmalı olduğunuz sualları müəyyənləşdirib real müsahibə formatında praktika etməyə kömək edəcəyik.",
      cta: "Müsahibəyə hazırlaş",
      noAccount: "İlkin baxış üçün hesab yaratmaq lazım deyil.",
      previewAria: "Nümunə müsahibə hazırlığı nəticəsi",
      previewLabel: "Müsahibəyə hazırlıq",
      previewCompany: "PASHA Bank",
      previewRole: "AI mühəndisi",
      previewStage: "Texniki müsahibə",
      sources: "Hazırlıq mənbələri",
      included: "Daxildir",
      available: "Mövcuddur",
      jobRequirements: "Vakansiya tələbləri",
      companySignals: "Şirkət siqnalları",
      focusAreas: "Ehtimal olunan fokus sahələri",
      rag: "RAG və LLM sistemləri",
      python: "Python",
      ml: "ML əsasları",
      deployment: "İstismara vermə",
      high: "Yüksək",
      medium: "Orta",
      questionCount: "34 ehtimal olunan sual",
      exampleQuestionLabel: "Nümunə sual",
      exampleQuestion: "Yekun LLM cavabından asılı olmadan axtarış keyfiyyətini necə qiymətləndirərdiniz?",
      jobDescription: "Vakansiya təsviri",
      onePreparation: "Bir hazırlıq",
      benefitsTitle: "Bir hazırlıqdan nə əldə edirsiniz",
      benefitsIntro: "Bir dəfə məlumat daxil etməklə həm fokuslanmış sual dəsti, həm də real müsahibə praktikası əldə edirsiniz.",
      benefits: [
        ["Vakansiyaya uyğun suallar", "Vəzifə tələbləri müsahibəçinin yoxlama ehtimalı yüksək olan sahələrə bölünür."],
        ["CV-nizdən yaranan suallar", "CV-dəki layihələr, texnologiyalar və iddialar real müsahibə follow-up suallarına çevrilir."],
        ["Müsahibəni praktika edin", "Seçilmiş sualları cavablandırın və cavablarınıza uyğun əlavə suallarla davam edin."],
      ],
      personalised: "Fərdiləşdirilmiş hazırlıq",
      personalisedTitle: "Müraciət etdiyiniz müsahibə əsasında hazırlanır",
      personalisedIntro: "Suallar seçilməzdən əvvəl vakansiya tələbləri CV-dəki təcrübə ilə əlaqələndirilir.",
      vacancyTitle: "AI mühəndisi vakansiyası",
      vacancySignals: ["Python", "RAG", "LLM qiymətləndirilməsi", "Docker", "Production ML"],
      cvSignalsTitle: "CV siqnalları",
      cvSignals: ["RAG platforması hazırlayıb", "FAISS ilə işləyib", "Docker ilə deploy edib"],
      likelyQuestions: "Ehtimal olunan suallar",
      sampleQuestions: [
        "RAG axtarış keyfiyyətini necə qiymətləndirdiniz?",
        "Niyə FAISS seçdiniz?",
        "Sistemi production mühitində necə izlədiniz?",
        "Hansı uğursuzluq halları ilə qarşılaşdınız?",
      ],
      recent: "Son hazırlıq",
      continuePreparing: "Hazırlığa davam edin",
      ready: "Hazır olduğunuz zaman",
      finalTitle: "Müsahibənizə hazırlaşın.",
      finalIntro: "Vəzifə və vakansiyanı əlavə edin. Ehtimal olunan suallarınız bir fokuslanmış hazırlıqda hazır olacaq.",
      start: "Hazırlığa başla",
      footer: "Konkret vəzifə və vakansiyalar üçün fokuslanmış hazırlıq.",
    },
    form: {
      eyebrow: "Yeni hazırlıq",
      title: "Hansı müsahibəyə hazırlaşdığınızı bizə bildirin.",
      intro: "Aşağıdakı məlumatları tamamlayın. Bu, cəmi bir neçə dəqiqə çəkəcək.",
      roleTitle: "Vəzifə məlumatları",
      roleIntro: "Şirkət və vəzifə ilə başlayın.",
      company: "Şirkət",
      role: "Vəzifə",
      jobLink: "Vakansiya linki",
      optional: "İstəyə bağlı",
      requirementsTitle: "Vakansiya tələbləri",
      requirementsIntro: "Sualların fərdiləşdirilməsi üçün ən güclü məlumat mənbəyidir.",
      jobDescription: "Vakansiya təsviri / Tələblər",
      jobPlaceholder: "Vakansiya təsvirini və ya tələbləri buraya əlavə edin...",
      characters: (count: number) => `${count} simvol · minimum 40`,
      interviewTitle: "Müsahibə məlumatları",
      interviewIntro: "Bildiyiniz məlumatları seçin. “Əmin deyiləm” seçimi tamamilə uyğundur.",
      seniority: "Təcrübə səviyyəsi",
      stage: "Müsahibə mərhələsi",
      language: "Müsahibə dili",
      cvTitle: "CV-nizi əlavə edin",
      cvIntro: "CV-dəki layihə, texnologiya və təcrübələr əsasında suallar əldə edin.",
      readyToReview: "Yoxlanmağa hazırdır",
      remove: "Sil",
      uploadStart: "CV-ni bura sürükləyin və ya",
      chooseFile: "fayl seçin",
      uploadMeta: "PDF və ya DOCX · maksimum 10 MB",
      cvExplanation: "CV əlavə etdikdə layihələriniz, bacarıqlarınız və təcrübəniz haqqında müsahibə sualları hazırlaya bilirik.",
      privacy: "Bu məlumatlardan yalnız müsahibə hazırlığı üçün istifadə edirik.",
      prepare: "Müsahibəni hazırla",
      invalidFile: "PDF və ya DOCX faylı seçin.",
      fileTooLarge: "CV faylı 10 MB-dan kiçik olmalıdır.",
      fileReadError: "CV faylını oxuya bilmədik. Faylı yenidən seçin.",
      prepareError: "Müsahibə hazırlığını yarada bilmədik. Məlumatları yoxlayıb yenidən cəhd edin.",
    },
    analysis: {
      eyebrow: "Müsahibəniz hazırlanır",
      title: (role: string) => `${role} vəzifəsi üçün fokuslanmış hazırlıq yaradılır.`,
      steps: ["Vəzifə təhlil edilir", "Vakansiya tələbləri oxunur", "CV yoxlanılır", "Uyğun müsahibə siqnalları araşdırılır", "Ehtimal olunan suallar hazırlanır"],
      noCv: "CV əlavə edilməyib — vəzifə və vakansiya məlumatları ilə davam edirik.",
    },
    preparation: {
      eyebrow: "Müsahibə hazırlığınız",
      coverageAria: "Şirkətə aid məlumatların əhatəsi",
      companyData: "Şirkətə aid məlumat",
      limited: "Məhdud",
      strong: "Güclü",
      liveResearch: "Canlı araşdırma",
      localPreview: "Lokal önbaxış",
      evidence: "Açıq mənbə sübutları",
      sourcesUsed: (count: number) => `${count} araşdırma mənbəsindən istifadə edilib`,
      companySignals: "Şirkət araşdırması",
      companySignalsTitle: "Sualları formalaşdıran təsdiqlənmiş siqnallar",
      companySignalsIntro: "Burada yalnız açıq mənbə ilə əlaqələndirilə bilən şirkət siqnalları göstərilir.",
      previewNote: "Canlı şirkət araşdırması əlçatan deyil. Bu suallar yalnız vakansiya və vəzifə nümunələrinə əsaslanır və şirkətə özəl kimi təqdim edilmir.",
      limitedNote: "Bu şirkət üçün açıq müsahibə məlumatı məhduddur. Suallar daha çox vakansiya, vəzifə, sahə və CV məlumatlarına əsaslanır.",
      strongNote: "Şirkətə aid siqnallar mövcuddur və vakansiya, vəzifə, sahə və CV məlumatları ilə birlikdə istifadə olunur.",
      likelyFocus: "Ehtimal olunan fokus",
      explore: "Bu müsahibədə nələr yoxlanıla bilər",
      focusIntro: "Vəzifə, vakansiya tələbləri və mövcud məlumatlar əsasında.",
      choose: "Hazırlıq üsulunu seçin",
      ready: "Suallarınız hazırdır",
      viewQuestions: "Suallara bax",
      viewQuestionsIntro: "Ehtimal olunan sualları və hər birinin niyə vacib olduğunu nəzərdən keçirin. Cavab vermək məcburi deyil.",
      practiceInterview: "Müsahibəni praktika et",
      practiceIntro: "Seçilmiş sualları cavablandırın və real əlavə suallar alın.",
    },
    questions: {
      sheet: "Hazırlıq vərəqi",
      title: "Ehtimal olunan müsahibə sualları",
      intro: "Vəzifə, vakansiya tələbləri, CV və mövcud müsahibə siqnalları əsasında seçilib.",
      cvReview: "CV icmalı",
      cvAreas: "CV-də araşdırıla biləcək sahələr",
      noCv: "CV əlavə edilməyib",
      noCvIntro: "Suallar vakansiya, vəzifə, sahə və müsahibə mərhələsinə əsaslanır. CV əlavə etmək üçün yeni hazırlıq başlada bilərsiniz.",
      filterAria: "Sualları kateqoriyaya görə filtrlə",
      all: "Bütün suallar",
      listAria: "Ehtimal olunan müsahibə sualları",
      why: "Bu sual niyə verilir?",
      approach: "Necə cavab verməliyəm?",
      practice: "Praktika et",
      whyTitle: "Niyə vacibdir",
      approachTitle: "Güclü cavab bunları əhatə etməlidir",
      evidence: "Mənbə",
    },
    practice: {
      eyebrow: "Müsahibə praktikası",
      title: "Praktika üsulunu seçin.",
      intro: "Bu müsahibə üçün xüsusi seçilmiş sualları cavablandırın və uyğun əlavə suallar alın.",
      chooseMode: "Rejimi seçin",
      real: "Real müsahibə",
      realIntro: "Rəy müsahibənin sonunda təqdim olunur.",
      practice: "Praktika",
      practiceIntro: "Praktika zamanı rəy alın.",
      focus: "Fokus",
      duration: "Müddət",
      focusLabels: { "Full Interview": "Tam müsahibə", Technical: "Texniki", "HR / Behavioral": "HR / Davranış", "CV Deep Dive": "CV üzrə ətraflı" },
      questionCount: (count: number) => `${count} uyğunlaşdırılmış sual mövcuddur`,
      start: "Müsahibəyə başla",
      modeLabels: { "Real Interview": "Real müsahibə", Practice: "Praktika" },
    },
    active: {
      end: "Müsahibəni bitir",
      questionProgress: (current: number, total: number) => `${total} sualdan ${current}-ci sual`,
      interviewer: "Müsahibəçi",
      selectedFrom: "Mənbə",
      followUpTopic: "Bu mövzu üzrə əlavə sual",
      answer: "Cavabınız",
      placeholder: "Cavabınızı müsahibədə deyəcəyiniz kimi yazın...",
      submit: "Cavabı göndər",
      feedback: "Praktika rəyi",
      feedbackTitle: "Cavabınızdakı sübutları gücləndirin.",
      strongPoints: "Güclü tərəflər",
      strongItems: ["Düşüncə xəttinizi izləmək üçün kifayət qədər kontekst verdiniz.", "Cavabınız əsas suala birbaşa toxundu."],
      improve: "Təkmilləşdirin",
      improveItems: ["Şəxsi töhfənizi daha aydın göstərin.", "Ölçülə bilən bir nəticə və ya qərar meyarı əlavə edin."],
      likelyFollowUp: "Ehtimal olunan əlavə sual",
      continue: "Davam et",
    },
    report: {
      complete: "Müsahibə tamamlandı",
      title: "Hazırlığınız üçün növbəti addım aydındır.",
      summary: (completed: number, mode: string) => `${mode} rejimində ${completed} sualı tamamladınız. Real müsahibədən əvvəl hər cavabın arxasındakı sübutları nəzərdən keçirin.`,
      worked: "Nə yaxşı alındı",
      keep: "Bunları davam etdirin",
      workedItems: ["Əlavə kontekstdən əvvəl suala cavab verin.", "Texniki seçimlərin arxasındakı məntiqi izah edin.", "Təcrübənizi hədəf vəzifə ilə əlaqələndirin."],
      improve: "Növbəti təkmilləşdirmə",
      credible: "Hər cavabı daha inandırıcı edin",
      improveItems: ["Mümkün olduqda nəticələri rəqəmlərlə göstərin.", "Ən azı bir real alternativi müqayisə edin.", "Şəxsən hansı hissəyə cavabdeh olduğunuzu aydınlaşdırın."],
      next: "Tövsiyə olunan növbəti addım",
      recommendation: "Ehtimal olunan sualları nəzərdən keçirin və ölçülə bilən iki nümunə hazırlayın.",
      viewQuestions: "Suallara bax",
      practiceAgain: "Yenidən praktika et",
    },
    stageLabels: azerbaijaniStageLabels,
    seniorityLabels: azerbaijaniSeniorityLabels,
    categoryLabels: azerbaijaniCategoryLabels,
    sourceLabels: azerbaijaniSourceLabels,
    interviewLanguageLabels: azerbaijaniInterviewLanguageLabels,
    focusAreaLabels: { rag: "RAG / LLM sistemləri", python: "Python və API mühəndisliyi", deployment: "Production mühitinə yerləşdirmə", decisions: "Texniki qərarvermə", evidence: "Aydın sübut və nəticələr", ownership: "Layihədə şəxsi məsuliyyət", technicalDecisions: "Texniki qərarlar", outcomes: "Ölçülə bilən nəticələr" },
    priorityLabels: { High: "Yüksək", Medium: "Orta" },
    specificityLabels: { "Company evidence": "Şirkət mənbəsi", Vacancy: "Vakansiya mənbəsi", "Role pattern": "Vəzifə nümunəsi" },
  },
} as const;

export type UiCopy = (typeof uiCopy)[UiLanguage];
